server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test-mybatis?useSSL=false
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


mybatis:
  # Spring boot integrated mybatis way to print sql
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      example:
        demo:
          repositories: debug
